name: ci-build
run-name: ${{ github.actor }}-ci-build
on: [push]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - run: nix-build ./.
